"""
ICAIF Track B: per-regime model−persistence Sharpe-gap table (LaTeX include).

Numbers are the Canonical Numbers from ICAIF_SUBMISSION_TODO.md (tranched daily
GMVP Sharpes; tuning 2008–2016 / held-out 2017–2021). Paper prints Regimes 1–4
via the locked numbering JSON.

Writes:
  results/regime_characterization/regime_performance_gaps.csv
  paper/tables/regime_performance.tex

Usage:
  .venv/bin/python -m scripts.analysis.regime.build_regime_performance_table
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[3]

# Canonical Numbers (model − persistence Sharpe gap). Do not invent alternatives.
# Source: ICAIF_SUBMISSION_TODO.md / REGIME_CONDITIONAL_ANALYSIS.md
CANONICAL_GAPS_BY_LEGACY: dict[str, dict[str, float]] = {
    "Calm Bull": {"tuning": 0.09, "held_out": -0.15},
    "Moderate Bull": {"tuning": -0.19, "held_out": -0.09},
    "Normal": {"tuning": 0.22, "held_out": 0.13},
    "High Stress": {"tuning": -0.30, "held_out": -0.04},
}


def build_table(numbering: dict) -> pd.DataFrame:
    legacy_by_paper = {int(k): v for k, v in numbering["legacy_name_by_paper_regime"].items()}
    rows = []
    for paper in (1, 2, 3, 4):
        legacy = legacy_by_paper[paper]
        g = CANONICAL_GAPS_BY_LEGACY[legacy]
        rows.append(
            {
                "paper_regime": paper,
                "legacy_name": legacy,  # bookkeeping only; not printed in LaTeX
                "gap_tuning": g["tuning"],
                "gap_held_out": g["held_out"],
                "era_consistent_positive": int(g["tuning"] > 0 and g["held_out"] > 0),
            }
        )
    return pd.DataFrame(rows)


def _fmt_gap(x: float) -> str:
    sign = "+" if x > 0 else ""
    return f"{sign}{x:.2f}"


def write_latex(df: pd.DataFrame, path: Path) -> None:
    lines = [
        "% Auto-generated by scripts/analysis/regime/build_regime_performance_table.py",
        "% Canonical Numbers only (ICAIF_SUBMISSION_TODO.md). Do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Per-regime model$-$persistence Sharpe gap on tranched daily GMVP "
        "returns. Tuning era is 2008--2016; held-out is 2017--2021. Regime~3 is the "
        "only era-consistent positive pocket (\\(\\approx\\)15--20\\% of days) and is "
        "not significant after multiple-testing considerations.}",
        "\\label{tab:regime-performance}",
        "\\begin{tabular}{lrr}",
        "\\toprule",
        "Regime & Tuning gap & Held-out gap \\\\",
        "\\midrule",
    ]
    for _, r in df.iterrows():
        star = "$^*$" if int(r.era_consistent_positive) == 1 else ""
        lines.append(
            f"{int(r.paper_regime)}{star} & {_fmt_gap(float(r.gap_tuning))} & "
            f"{_fmt_gap(float(r.gap_held_out))} \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\vspace{0.35em}",
            "\\begin{minipage}{\\linewidth}\\footnotesize $^*$Only era-consistent "
            "positive pocket; insignificant after multiple testing.\\end{minipage}",
            "\\end{table}",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--numbering",
        default=str(REPO_ROOT / "results" / "regime_characterization" / "paper_regime_numbering.json"),
    )
    args = ap.parse_args()

    numbering = json.loads(Path(args.numbering).read_text())
    df = build_table(numbering)

    out_dir = REPO_ROOT / "results" / "regime_characterization"
    out_dir.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_dir / "regime_performance_gaps.csv", index=False)
    write_latex(df, REPO_ROOT / "paper" / "tables" / "regime_performance.tex")

    print("Per-regime model−persistence Sharpe gaps (Canonical Numbers):")
    print(df.to_string(index=False))
    print(f"\nWrote: {out_dir / 'regime_performance_gaps.csv'}")
    print(f"Wrote: {REPO_ROOT / 'paper' / 'tables' / 'regime_performance.tex'}")


if __name__ == "__main__":
    main()
